# Лабораторная работа №7
## Исследование рекуррентной нейронной сети Хопфилда на примере задачи распознавания образов

In [15]:
import numpy as np
import matplotlib.pyplot as plt

from itertools import chain

In [8]:
# Функционирование в синхронном режиме
f = lambda net: net
netF = lambda W, Y, k: sum(w * y for idx, (w, y) in enumerate(zip(W, Y)) if idx != k)
actF = lambda net: 1 if net > 0 else (-1 if net < 0 else f(net))

In [28]:
# Образы согласно варианту
A = [
    [-1,  1, -1],
    [ 1, -1,  1],
    [ 1,  1,  1],
    [ 1, -1,  1],
    [ 1, -1,  1]
]

I = [
    [ 1,  1,  1],
    [-1,  1, -1],
    [-1,  1, -1],
    [-1,  1, -1],
    [ 1,  1,  1]
]

F = [
    [ 1,  1,  1],
    [ 1, -1, -1],
    [ 1,  1, -1],
    [ 1, -1, -1],
    [ 1, -1, -1]
]

# Векторизуем
A, I, F = [
    np.fromiter(
        chain(*np.transpose(img)),
        dtype=int
    ) for img in [A, I, F]
]

# Вывод
A, I, F

(array([-1,  1,  1,  1,  1,  1, -1,  1, -1, -1, -1,  1,  1,  1,  1]),
 array([ 1, -1, -1, -1,  1,  1,  1,  1,  1,  1,  1, -1, -1, -1,  1]),
 array([ 1,  1,  1,  1,  1,  1, -1,  1, -1, -1,  1, -1, -1, -1, -1]))

In [42]:
def create(imgs):
    # Начальные веса как векторная сумма матричных произведений образов на транспонированных себя же
    W = sum(np.dot(np.transpose([img]), [img]) for img in imgs)

    # Зануляем диагональ
    np.fill_diagonal(W, 0)

    return W, imgs

def operate(W, Y, img):
    

create([A, I, F])

array([[ 0, -1, -1, -1,  1,  1,  1,  1,  1,  1,  3, -3, -3, -3, -1],
       [-1,  0,  3,  3,  1,  1, -3,  1, -3, -3, -1,  1,  1,  1, -1],
       [-1,  3,  0,  3,  1,  1, -3,  1, -3, -3, -1,  1,  1,  1, -1],
       [-1,  3,  3,  0,  1,  1, -3,  1, -3, -3, -1,  1,  1,  1, -1],
       [ 1,  1,  1,  1,  0,  3, -1,  3, -1, -1,  1, -1, -1, -1,  1],
       [ 1,  1,  1,  1,  3,  0, -1,  3, -1, -1,  1, -1, -1, -1,  1],
       [ 1, -3, -3, -3, -1, -1,  0, -1,  3,  3,  1, -1, -1, -1,  1],
       [ 1,  1,  1,  1,  3,  3, -1,  0, -1, -1,  1, -1, -1, -1,  1],
       [ 1, -3, -3, -3, -1, -1,  3, -1,  0,  3,  1, -1, -1, -1,  1],
       [ 1, -3, -3, -3, -1, -1,  3, -1,  3,  0,  1, -1, -1, -1,  1],
       [ 3, -1, -1, -1,  1,  1,  1,  1,  1,  1,  0, -3, -3, -3, -1],
       [-3,  1,  1,  1, -1, -1, -1, -1, -1, -1, -3,  0,  3,  3,  1],
       [-3,  1,  1,  1, -1, -1, -1, -1, -1, -1, -3,  3,  0,  3,  1],
       [-3,  1,  1,  1, -1, -1, -1, -1, -1, -1, -3,  3,  3,  0,  1],
       [-1, -1, -1, -1,  1,  1,  1

In [14]:
a = [
    [1, 2],
    [3, 4]
]
b = [
    [2, 3],
    [4, 5]
]
dot(a, b)

[[10, 13], [22, 29]]